export const RENDER_DEFAULTS = {
    background: "#000000",
    exposure: 0.97,
    environment: 0.28,
    bloom: 0,
    bloomThreshold: 0,
    noise: 0,
    toneMapping: "Neutral",
    occlusion: !0,
    occlusionStrength: 0.6,
    dof: !1,
    dofAperture: 13,
    dofBlur: 0.04,
    dofRange: 0.3,
  };
export const FINISH_PRESETS = {
    Glossy: { roughness: 0.1, clearcoat: 1, coatRoughness: 0.08 },
    Satin: { roughness: 0.3, clearcoat: 0.45, coatRoughness: 0.3 },
    Matte: { roughness: 0.62, clearcoat: 0.06, coatRoughness: 0.7 },
  };
export const MATERIAL_PRESETS = {
    Holo: {
      material: {
        finish: "Matte",
        baseColor: "#20242d",
        holoIntensity: 3.78,
        holoScale: 400,
        bandFreq: 1.1,
        saturation: 1,
        hueShift: 0.37,
        sparkle: 0.73,
        specTint: 0.33,
        iridescence: 0.81,
        metalness: 1,
        sheen: 0,
        bump: 3,
        bumpTiling: 3,
        ...FINISH_PRESETS.Matte,
      },
      render: { ...RENDER_DEFAULTS },
    },
    Chrome: {
      material: {
        finish: "Glossy",
        baseColor: "#dfe3e8",
        holoIntensity: 0,
        sparkle: 0.2,
        specTint: 0,
        iridescence: 0,
        metalness: 1,
        sheen: 0,
        bump: 0.05,
        ...FINISH_PRESETS.Glossy,
        roughness: 0.04,
        coatRoughness: 0.04,
      },
      render: { ...RENDER_DEFAULTS },
    },
    "Black Cloth": {
      material: {
        finish: "Matte",
        baseColor: "#101114",
        holoIntensity: 0.1,
        holoScale: 8,
        bandFreq: 0.2,
        saturation: 0,
        hueShift: 0,
        sparkle: 0,
        specTint: 0.15,
        iridescence: 0,
        metalness: 0,
        sheen: 0,
        bump: 0.57,
        bumpTiling: 5.5,
        ...FINISH_PRESETS.Matte,
        roughness: 0.7,
        clearcoat: 0,
        coatRoughness: 0,
      },
      render: { ...RENDER_DEFAULTS },
    },
  };
